// pages/index.js
import Head from "next/head";
import Image from "next/image";

import dynamic from "next/dynamic";

import BannerComponent from "@/components/BannerComponent";
import Globals from "@/modules/Globals";
const ServiceSectionComponent = dynamic(() => import('@/components/ServiceSectionComponent'));
const CtaBannerComponent = dynamic(() => import('@/components/CtaBannerComponent'));
const PreviousWorksComponents = dynamic(() => import('@/components/PreviousWorksComponents'));
const DownloadCatelogue = dynamic(() => import('@/components/DownloadCatelogue'));


export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BannerComponent />

      <section className="about-us-section-wrapper">
        <div className="container-xl">
          <div className="row">
            <div className="col-lg-6 mb-4 mb-lg-0">
              <div className="left-container">
                <p className="section-heading">
                  Meet the <strong>Skilled Team</strong> of Creation House, Your <strong>Stand Builder</strong> for <strong>Events</strong> and <strong>Exhibitions</strong>
                </p>
                <p className="description">In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available...</p>
                <span className="read-more">Read More</span>
              </div>
            </div>
            <div className="col-lg-6 d-flex justify-content-center">
              <div className="masonry-container">
                <div className="masonry-item large-item">
                  <Image width={400} height={400} src={`${Globals.BASE_URL}assets/imgs/about-img-1.JPG`} alt="" quality={100} />
                </div>
                <div className="masonry-item small-item">
                  <Image width={400} height={400} src={`${Globals.BASE_URL}assets/imgs/about-img-2.JPG`} alt="" quality={100}/>
                </div>
                <div className="masonry-item medium-item">
                  <Image width={400} height={400} src={`${Globals.BASE_URL}assets/imgs/about-img-3.JPG`} alt=""   quality={100}/>
                </div>
              </div>

            </div>
          </div>
        </div>
      </section>

      <ServiceSectionComponent />
      <CtaBannerComponent />
      <PreviousWorksComponents />
      <DownloadCatelogue />




    </>
  );
}
